---
- hosts: localhost
  tasks:
    - name: Install telegraf
      yum:
        name: telegraf
        state: latest
      become: yes

    - name: Copy config
      copy:
        src: ./telegraf.conf
        dest: /etc/telegraf/telegraf.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
        force: no
        notify:
        - restart telegraf
      become: yes

  handlers:
   - name: restart telegraf
     service:
       name: telegraf
       state: restarted
     become: yes
