---
- hosts: localhost
  tasks:
    - name: Add Grafan repo
      yum_repository:
        name: grafana
        description: Grafana repo
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: no
      become: yes

    - name: Import Grafana GPG signing key
      yum:
        name: grafana 
        state: present
      become: yes

    - name: Install Grafana
      yum:
        name: grafana
        state: present
      become: yes

    - name: grafana is installed
      yum:
        name: grafana
        state: installed
      become: yes

    - name: grafana is running and enabled
      service:
        name: grafana-server
        state: started
        enabled: yes
      become: yes
